### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by dgasmith** [loriab/planets#1]
Please add a license so that I can use your code!

**Comment by loriab** [comment]
A user! What license would you like?

**Comment by dgasmith** [comment]
LGPL please!

**Comment by loriab** [comment]
I will approve a LGPL-3.0 PR. I don't like LGPL-2.1

**Comment by dgasmith** [comment]
Ok, is there a link to the license?

**Comment by loriab** [comment]
https://opensource.org/licenses/LGPL-3.0 is the license. I hear there's instructions at https://www.gnu.org/licenses/gpl-howto.en.html.
